
import React, { useCallback } from 'react'; 
import {useForm, SubmitHandler} from 'react-hook-form';
import {FaLinkedin, FaGithub, FaFacebook, FaTwitter, FaCopyright } from 'react-icons/fa'

import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import FormSignUp from '../components/Form';
import Footer from '../components/Footer';


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Daily UI - Sign Up Page </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> 
      </Head>
      <main>
        <FormSignUp />
      </main>
      <Footer />
    </div>
  )
}

export default Home;
